services:
  - type: web
    name: graeseo-server
    runtime: java
    buildCommand: ./gradlew build -x test
    startCommand: java -jar build/libs/server-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 19
    autoDeploy: true
